[tool.poetry]
name = "ric-sapasap"
version = "0.1.0"
description = ""
authors = ["Ric Janus Sapasap <me@ricjanus.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
markdown = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
